### PR TITLE
add support for freeform comments

### PR DESCRIPTION
**Pull request by maxandersen**
To allow detecting issues/discussion with "CVE" or "vulnerability" and add a comment pointing users to security.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
I decided to go with a separate comment rather than merging them all.

Better have concerns properly separated.

**Comment by gsmet** [comment]
Also we should probably be a bit careful when deploying that and check that it brings some value and doesn't confuse people.

**Comment by maxandersen** [comment]
Reason I put in one comment was to not trigger two notifications. 

For cve/security one it will be rare (I assume) but for others it could be more often. so yeah - just need to be careful :)

**Comment by gsmet** [comment]
Yeah but adding unrelated things in the same comment will be confusing as hell.

But in any case, we need to use this feature carefully as it can quickly be annoying (pushing comments that are not really useful).

**Pull request merged**
