### PR TITLE
Check pr commits 

### LINKED ISSUE #236: Add checks for commits in pull requests
We should check that:

- A PR does not contain merge commits (and prevent merging if so)
- A PR does not contain a fixup commit (and prevent merging if so)

Using the check API is the way to go and @yrodiere implemented checks here: https://github.com/hibernate/hibernate-github-bot/tree/main/src/main/java/org/hibernate/infra/bot and it could serve as an inspiration.

### PR DESCRIPTION
**Pull request by nicolasgras**
This pull request resolves #236 (Add checks for commits in pull requests)
A new feature has been defined to check if PR's commit list contains any merge or fixup commit and check run are created in PR to show results.

- If any merge commit if found in PR, then a check run is in FAILURE in PR and user can see which commits are involved. Otherwise, check run for merge commit analysis is in SUCCESS.
- If any fixup commit if found in PR, then a check run is in FAILURE in PR and user can see which commits are involved. Otherwise, check run for fixup commit analysis is in SUCCESS.

image
image

### CODE REVIEW

**Comment by gsmet** [comment]
I rebased to remove the merge commits. Believe it or not, we don't want them ;).

I also added a commit with some minor editorialization and dropped the `Edited` event as we don't want to run the checks just because the description has changed.
We might tweak that later if we add more rules.

**Comment by gsmet** [comment]
Thanks, nice work!

**Comment by gsmet** [comment]
I just deployed the new version.

**Comment by nicolasgras** [comment]
My pleasure. Thanks for the review and the merge. :)

**Pull request merged**
