### PR TITLE
Add ability to push items to a given project

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
/cc @maxandersen @ebullient 

(this was excessively painful - note that the Documentation board is using the Classic projects so for now we can't use this feature for it)

**Review by ebullient — APPROVED** [review]
🥰🎉

**Comment by maxandersen** [comment]
Nice! My current Attempt stalled by dealing with custom graphql. I assume that was part of the pain? :)

@ebullient can doc move to new project api so it Can use it ?

**Comment by gsmet** [comment]
@maxandersen in the end, I was able to implement something for both types of projects.

**Comment by maxandersen** [comment]
Sweet!

Does it use same syntax in the config?

**Comment by gsmet** [comment]
Same syntax but 2 different roots: https://github.com/quarkusio/quarkus/pull/27028/files .

**Comment by maxandersen** [comment]
Awesome

**Pull request merged**
